###########################
#####                 #####
####                   ####
###   Author: HALD91    ###
###   Version: 1.5.1.7  ###
####                   ####
#####                 #####
###########################

## Set Your prefix here:
Prefix: '&7[&3WeaponKit&7]'

##NetherWart Kit
NetherWartKit:
  Enchantments: true
  Soulbound: true
  Name: '&5Weaponkit'

## Wither Armor
Armor:
  WitherHelmet:
    Enchantments: true
    Soulbound: true
    Name: '&5Wither Helmet'
  WitherChestPlate:
    Enchantments: true
    Soulbound: true
    Name: '&5Wither ChestPlate'
  WitherLeggings:
    Enchantments: true
    Soulbound: true
    Name: '&5Wither Leggings'
  WitherBoots:
    Enchantments: true
    Soulbound: true
    Name: '&5Wither Boots'

## Poison Axe
PoisonAxeConfig:
  Soulbound: true
  Enchantments: true
  Name: '&5PoisonAxe'

## Nausea Axe
NauseaAxeConfig:
  Soulbound: true
  Enchantments: true
  Name: '&3NauseaAxe'

## Blindness Axe
BlindnessAxeConfig:
  Soulbound: true
  Enchantments: true
  Name: '&6BlindnessAxe'

## Wither Axe
WitherAxeConfig:
  Soulbound: true
  Enchantments: true
  Name: '&5WitherAxe'

## Poison Sword
PoisonSwordConfig:
  Soulbound: true
  Enchantments: true
  Name: '&5PoisonSword'

## Nausea Sword
NauseaSwordConfig:
  Soulbound: true
  Enchantments: true
  Name: '&3NauseaSword'

## Blindness Sword
BlindnessSwordConfig:
  Soulbound: true
  Enchantments: true
  Name: '&6BlindnessSword'

## Wither Sword
WitherSwordConfig:
  Soulbound: true
  Enchantments: true
  Name: '&5WitherSword'
